"""Reusable local API for StructVision's frozen classical baseline."""

from .api import StructuralAnomalyDetector
from .configuration import (
    DetectorConfig,
    FeatureConfig,
    PreprocessingConfig,
    ProposalConfig,
    ScoringConfig,
)
from .executor import ExperimentExecutorV2, ExperimentSample, V2ExecutionReport
from .errors import *
from .sinks import (
    ArtifactSink,
    MemoryResultSink,
    NullArtifactSink,
    NullResultSink,
    ResultSink,
    V2SQLiteResultSink,
)
from .types import AnalysisResult, AnalysisSample, BatchAnalysisResult, BatchFailure, Proposal
from .demonstration import (
    CLASSICAL_METHOD,
    DEFAULT_METHOD,
    EVIDENCE_ROWS,
    FIXTURE_LABELS,
    HYBRID_METHOD,
    METHOD_STATUSES,
    PATCHCORE_METHOD,
    DecodedDemonstrationImage,
    DemonstrationAnalysis,
    DemonstrationArtifactError,
    DemonstrationInputError,
    LearnedEnvironmentUnavailableError,
    LearnedRuntimePaths,
    MethodAvailability,
    MethodStatus,
    analyse_demonstration_image,
    analysis_json_bytes,
    annotated_png_bytes,
    binary_mask_png_bytes,
    candidate_crop,
    candidate_mask,
    candidate_rows,
    decode_image_bytes,
    demonstration_fixture,
    export_payload,
    method_availability,
    method_status,
    pipeline_stages,
    proposal_csv_bytes,
    render_anomaly_overlay,
    render_overlay,
    technical_summary_bytes,
)

__all__ = [
    "AnalysisResult",
    "AnalysisSample",
    "ArtifactSink",
    "BatchAnalysisResult",
    "BatchFailure",
    "DetectorConfig",
    "FeatureConfig",
    "ExperimentExecutorV2",
    "ExperimentSample",
    "MemoryResultSink",
    "NullArtifactSink",
    "NullResultSink",
    "PreprocessingConfig",
    "Proposal",
    "ProposalConfig",
    "ResultSink",
    "ScoringConfig",
    "StructuralAnomalyDetector",
    "V2SQLiteResultSink",
    "V2ExecutionReport",
    "CLASSICAL_METHOD",
    "DEFAULT_METHOD",
    "EVIDENCE_ROWS",
    "FIXTURE_LABELS",
    "HYBRID_METHOD",
    "METHOD_STATUSES",
    "PATCHCORE_METHOD",
    "DecodedDemonstrationImage",
    "DemonstrationAnalysis",
    "DemonstrationArtifactError",
    "DemonstrationInputError",
    "LearnedEnvironmentUnavailableError",
    "LearnedRuntimePaths",
    "MethodAvailability",
    "MethodStatus",
    "analyse_demonstration_image",
    "analysis_json_bytes",
    "annotated_png_bytes",
    "binary_mask_png_bytes",
    "candidate_crop",
    "candidate_mask",
    "candidate_rows",
    "decode_image_bytes",
    "demonstration_fixture",
    "export_payload",
    "method_availability",
    "method_status",
    "pipeline_stages",
    "proposal_csv_bytes",
    "render_anomaly_overlay",
    "render_overlay",
    "technical_summary_bytes",
]

__version__ = "1.0.0"
